/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuhyaRouteImport } from './routes/venuhya'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as GayatriRouteImport } from './routes/gayatri'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as IndexRouteImport } from './routes/index'

const VenuhyaRoute = VenuhyaRouteImport.update({
  id: '/venuhya',
  path: '/venuhya',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const GayatriRoute = GayatriRouteImport.update({
  id: '/gayatri',
  path: '/gayatri',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/gayatri': typeof GayatriRoute
  '/intro': typeof IntroRoute
  '/venuhya': typeof VenuhyaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/gayatri': typeof GayatriRoute
  '/intro': typeof IntroRoute
  '/venuhya': typeof VenuhyaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/gayatri': typeof GayatriRoute
  '/intro': typeof IntroRoute
  '/venuhya': typeof VenuhyaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details' | '/gayatri' | '/intro' | '/venuhya'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/gayatri' | '/intro' | '/venuhya'
  id: '__root__' | '/' | '/details' | '/gayatri' | '/intro' | '/venuhya'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  GayatriRoute: typeof GayatriRoute
  IntroRoute: typeof IntroRoute
  VenuhyaRoute: typeof VenuhyaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venuhya': {
      id: '/venuhya'
      path: '/venuhya'
      fullPath: '/venuhya'
      preLoaderRoute: typeof VenuhyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gayatri': {
      id: '/gayatri'
      path: '/gayatri'
      fullPath: '/gayatri'
      preLoaderRoute: typeof GayatriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  GayatriRoute: GayatriRoute,
  IntroRoute: IntroRoute,
  VenuhyaRoute: VenuhyaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
